### PR TITLE
[NFC] Invert color diagnostics flag

### PR DESCRIPTION
**Pull request by CodaFi**
### What's in this pull request?

Replace `--no-colors` with `--color-diagnostics`.  Not as good a UX on the command line, but we spend most of our time writing tests anyways.

### CODE REVIEW

**Review by harlanhaskins — COMMENTED** [review]
I wonder if we can be smarter.

**Comment by CodaFi** [comment]
The frontend can choose to enable colors when we arent executing a verb, but we dont yet provide a full compile job.

**Comment by CodaFi** [comment]
⛵️

**Comment by segiddins** [comment]
> I wonder if we can be smarter.

could check if stdout / stderr isatty ?

**Pull request merged**
