### PR TITLE
Add tool for running diagnostic verifier tests

### PR DESCRIPTION
**Pull request by harlanhaskins**
This introduces a tool called `lite` that will search recursively through a directory for tests and executes them.

To create a `lite` test, add one or more `RUN:` lines to a `.silt` file, like so:

```haskell
-- RUN: --verify parse
module Foo where

id x = x
```

And `lite` will find the file and invoke
```bash
${just_built_silt} --verify parse ${this_file}
```

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@codafi Good to merge? I want to make it simple to add tests. Maybe I should write a `Testing.md` document explaining how to use this...

**Comment by CodaFi** [comment]
One request: `not` modifier.  Tool should care about passing/failing to execute the action.

**Comment by harlanhaskins** [comment]
Does `-- RUN-NOT: --verify parse` work? The `not` tool in LLVM is just a binary that forwards arguments, and `lite` only knows how to invoke `silt`.

**Comment by CodaFi** [comment]
That’s just fine by me.

**Comment by harlanhaskins** [comment]
Check `Tests/Lite/Lite/test-run-not.silt` for an example of a passing `RUN-NOT:` test.

**Comment by harlanhaskins** [comment]
@codafi Good to merge? I'd love to see the test cases you come up with.

**Review by CodaFi — APPROVED** [review]

**Pull request merged**
