### PR TITLE
Add Hasher protocol and a stable hasher

### PR DESCRIPTION
**Pull request by CodaFi**
### What's in this pull request?

- Adds a new library, libBoring,  to separate data structures needed for the dependency graph work in #88.
- Adds a copy of the `Hasher` protocol that's pending in Swift evolution.  The hope is we remove our copy of it when the proposal is accepted
- Implement SipHash24 as a first stable hasher

### CODE REVIEW

**Comment by harlanhaskins** [comment]
Where did the siphash implementation come from?

**Comment by CodaFi** [comment]
https://github.com/silt-lang/silt/pull/123/files#diff-f42be44244f6afb321ac307066dc5642R10

**Review by harlanhaskins — APPROVED** [review]
Love the library name.

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
