### PR TITLE
[NFC] Miscellaneous Nits

### PR DESCRIPTION
**Pull request by CodaFi**
### What's in this pull request?

- Fix the last two swiftlint errors I left in source.
- Teach SyntaxGen to emit `2017-\(currentYear)`
- Move `Notation` into its own file (and comment out something that won't quite work without the reparsing patch).

### CODE REVIEW

**Comment by harlanhaskins** [comment]
Can you run SyntaxGen again while you’re at it?

**Comment by CodaFi** [comment]
> Can you run SyntaxGen again while you’re at it?

You already changed the right files, you just didn't update the template 😄

**Comment by harlanhaskins** [comment]
Ha! Right! Did you fix the issues in the last PR?

**Comment by CodaFi** [comment]
Using these splits to tackle as much of the NFC-y ones up front and to reduce the size of the diff.

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
