### PR TITLE
Removed YAML dependency and specify nodes in Swift

### PR DESCRIPTION
**Pull request by harlanhaskins**
This patch removes all the YAML specifications for Syntax and Token nodes and instead just declares them in Swift. It's way simpler and requires less special logic for finding the files and whatnot.

This mimics what SwiftSyntax does, though we have the benefit of generating code in Swift vs. Python.

### CODE REVIEW

**Review by CodaFi — APPROVED** [review]
An excellent simplification!  One question though

**Comment by CodaFi** [comment]
The overload that creates `SyntaxCollection` subclasses is never refined further.  Do you think it would be advisable to remove the need for a magic string `”SyntaxCollection”`?

**Comment by harlanhaskins** [comment]
You mean just assuming if an `element` is present without the kind? Maybe making two initializers, one that an element and one that takes a kind?

**Comment by CodaFi** [comment]
> You mean just assuming if an element is present without the kind? Maybe making two initializers, one that an element and one that takes a kind?

Yeah

**Comment by harlanhaskins** [comment]
👍

**Comment by harlanhaskins** [comment]
:boat:

**Pull request merged**
