### PR TITLE
Patch the outer core.

### PR DESCRIPTION
**Pull request by dan-zheng**
Patch the upper outer core, making it more robust.

### CODE REVIEW

**Comment by CodaFi** [comment]
⛵️

**Comment by dan-zheng** [comment]
> ⛵️

What's up with the sail 👀

**Comment by CodaFi** [comment]
I learned to review patches in emoji from the Github folks.  They use :shipit: or 🚢 as an alias for "LGTM", but I don't like the way that boat looks...

**Comment by dan-zheng** [comment]
I see 🤯

**Pull request merged**
