### PR TITLE
Adding swiftlint steps to CI config.

### PR DESCRIPTION
**Pull request by stupergenius**
Addresses #12 by adding a simple `swiftlint` step to both Linux and macOS builds. The linux side could use a little cleanup at this point. 🏚

### CODE REVIEW

**Comment by harlanhaskins** [comment]
Thanks! Unfortunately this is gonna cause a failure because the actual repo doesn’t follow the default SwiftLint style 😅

Any chance you could branch off of #18 to include these changes? I think your .travis.yml is better than what I have, especially since it supports Linux!

**Comment by stupergenius** [comment]
Ah yeah np @harlanhaskins. I'll close this and rebase the changes (or some other git sorcery) once I get it to actually run (and fail).

**Comment by harlanhaskins** [comment]
Yeah, also unfortunately Travis usually doesn’t have a Mac box free for testing so it can take a very long time...

**Comment by stupergenius** [comment]
Alright branch and PR rebased to the `scotch-brite™-brand-lint-roller` branch. The build breaks on a compiler error now, but both platform linters pass.

**Comment by harlanhaskins** [comment]
This looks great! Thanks for tackling this! 😄

**Pull request merged**
